services:
  nodejs:
    from: 'node:0.12.2'

staging:
  prepare:
    - npm install
  service: nodejs
  folder: /app
  port: 5000
  cmd: bin/web
  env:
    - NODE_ENV=production
    - PORT=80

tests:
  prepare:
    - npm install
  service: nodejs
  folder: /app
  cmd: 'echo "........"'
  env:
    - NODE_ENV=production
